main: main.cpp RaycastingEngine.cpp Ray.cpp Player.cpp -lsfml-graphics -lsfml-window -lsfml-system
	g++ -Wall -o test main.cpp RaycastingEngine.cpp Ray.cpp Player.cpp -lsfml-graphics -lsfml-window -lsfml-system
	./test