main: main.cpp RaycastingEngine.cpp Ray.cpp Player.cpp Weapon.cpp Semi.cpp Auto.cpp Shotgun.cpp Pistol.cpp MG.cpp Enemy.cpp
	g++ -Wall -o test main.cpp RaycastingEngine.cpp Ray.cpp Player.cpp Weapon.cpp Semi.cpp Auto.cpp Shotgun.cpp Pistol.cpp MG.cpp Enemy.cpp -lsfml-graphics -lsfml-window -lsfml-system
	./test