main: main.cpp RaycastingEngine.cpp Ray.cpp Player.cpp Weapon.cpp Semi.cpp Auto.cpp Shotgun.cpp Pistol.cpp MG.cpp Enemy.cpp
	g++ -Wall -o test main.cpp RaycastingEngine.cpp Ray.cpp Player.cpp Weapon.cpp Semi.cpp Auto.cpp Shotgun.cpp Pistol.cpp MG.cpp Enemy.cpp -lsfml-graphics -lsfml-window -lsfml-system
	./test




testAngle: TestAngle.cpp RaycastingEngine.cpp Ray.cpp Player.cpp Weapon.cpp Semi.cpp Auto.cpp Shotgun.cpp Pistol.cpp MG.cpp Enemy.cpp
	g++ -Wall -o test TestAngle.cpp RaycastingEngine.cpp Ray.cpp Player.cpp Weapon.cpp Semi.cpp Auto.cpp Shotgun.cpp Pistol.cpp MG.cpp Enemy.cpp -lsfml-graphics -lsfml-window -lsfml-system
	./test

testRay: TestRay.cpp RaycastingEngine.cpp Ray.cpp Player.cpp Weapon.cpp Semi.cpp Auto.cpp Shotgun.cpp Pistol.cpp MG.cpp Enemy.cpp
	g++ -Wall -o test TestRay.cpp RaycastingEngine.cpp Ray.cpp Player.cpp Weapon.cpp Semi.cpp Auto.cpp Shotgun.cpp Pistol.cpp MG.cpp Enemy.cpp -lsfml-graphics -lsfml-window -lsfml-system
	./test

testHit: TestHit.cpp RaycastingEngine.cpp Ray.cpp Player.cpp Weapon.cpp Semi.cpp Auto.cpp Shotgun.cpp Pistol.cpp MG.cpp Enemy.cpp
	g++ -Wall -o test TestHit.cpp RaycastingEngine.cpp Ray.cpp Player.cpp Weapon.cpp Semi.cpp Auto.cpp Shotgun.cpp Pistol.cpp MG.cpp Enemy.cpp -lsfml-graphics -lsfml-window -lsfml-system
	./test

testScore: TestScore.cpp RaycastingEngine.cpp Ray.cpp Player.cpp Weapon.cpp Semi.cpp Auto.cpp Shotgun.cpp Pistol.cpp MG.cpp Enemy.cpp
	g++ -Wall -o test TestScore.cpp RaycastingEngine.cpp Ray.cpp Player.cpp Weapon.cpp Semi.cpp Auto.cpp Shotgun.cpp Pistol.cpp MG.cpp Enemy.cpp -lsfml-graphics -lsfml-window -lsfml-system
	./test